name: Java CI (Maven)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Inject Main-Class into JAR
        run: |
          echo "Main-Class: com.mycompany.addressbook.Main" > MANIFEST.MF
          echo "Class-Path: ." >> MANIFEST.MF
          jar umf MANIFEST.MF target/*.jar
          jar tf target/*.jar | head -n 10

      - name: Upload artifact (JAR ejecutable)
        uses: actions/upload-artifact@v4
        with:
          name: AddressBookJava
          path: target/*.jar
          if-no-files-found: error
